version: 2
updates:
  # Expo project using npm
  - package-ecosystem: "npm"
    directory: "/" # root directory where package.json is
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  # GitHub Actions (keep your workflows fresh!)
  - package-ecosystem: "github-actions"
    directory: "/" # .github/workflows is default
    schedule:
      interval: "weekly"
