import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  form: {
    width: "90%",
    paddingVertical: 40,
    alignItems: "center",
    minHeight: "100%",
  },
  title: {
    fontSize: 24,
    marginBottom: 30,
    marginTop: 20,
    color: "#fff",
    fontWeight: "600",
  },
  input: {
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#B9B9B9",
    color: "#fff",
    fontSize: 16,
    marginBottom: 24,
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  passwordContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    marginBottom: 24,
  },
  passwordInput: {
    marginBottom: 0,
    paddingRight: 50, // Make room for the eye icon
  },
  eyeIcon: {
    position: "absolute",
    right: 0,
    height: "100%",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingBottom: 12,
  },
  socialButtons: {
    width: "100%",
    height: 100,
    flexDirection: "column",
    justifyContent: "space-between",
    marginTop: 30,
  },
  socialButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 20,
    marginBottom: 30,
    width: "100%",
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#181818",
  },
  checkboxBoxChecked: {
    borderColor: "#6646EC",
  },
  checkboxCheck: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  checkboxText: {
    color: "#B9B9B9",
    fontSize: 14,
    marginLeft: 12,
    flex: 1,
    flexWrap: "wrap",
    lineHeight: 20,
  },
  link: {
    textDecorationLine: "underline",
    color: "#fff",
  },
  signInText: {
    color: "#B9B9B9",
    width: "100%",
    fontSize: 14,
    marginTop: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  signupButton: {
    width: "100%",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    backgroundColor: "transparent",
  },
  signupButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  passwordMismatchText: {
    color: "#ff6b6b",
    fontSize: 12,
    marginTop: 4,
    marginBottom: 4,
  },
  passwordRequirements: {
    width: "100%",
    marginTop: 8,
    marginBottom: 20,
  },
  requirementMet: {
    color: "#4CAF50",
  },
  centerContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    minHeight: 400,
  },
  loadingText: {
    color: "#fff",
    fontSize: 16,
    marginTop: 16,
  },
  successTitle: {
    color: "#fff",
    fontSize: 24,
    marginBottom: 16,
  },
  successText: {
    color: "grey",
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
});
